import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Navbar, NavbarBrand, NavbarContent, NavbarItem} from "@heroui/navbar";
import {Link} from "@heroui/link";
import {Button} from "@heroui/button";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const AcmeLogo = () => {
    return (
        <svg fill="none" height="36" viewBox="0 0 32 32" width="36">
            <path
                clipRule="evenodd"
                d="M17.6482 10.1305L15.8785 7.02583L7.02979 22.5499H10.5278L17.6482 10.1305ZM19.8798 14.0457L18.11 17.1983L19.394 19.4511H16.8453L15.1056 22.5499H24.7272L19.8798 14.0457Z"
                fill="currentColor"
                fillRule="evenodd"
            />
        </svg>
    );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased light min-h-screen overflow-x-hidden`}
      >
      <Navbar className="py-3 bg-gradient-to-r from-blue-900 to-indigo-900 text-white backdrop-blur-xl
  border-b border-white/10 ">
          <NavbarBrand>
              <AcmeLogo />
              <p className="font-bold text-inherit">VAR Analytics</p>
          </NavbarBrand>
          <NavbarContent className="hidden sm:flex gap-4" justify="center">
              <NavbarItem>
                  <Button
                      as={Link}
                      href="/club/36"
                      radius="full"
                      color="primary"
                      variant="light"
                      className="text-white text-base font-medium"
                  >
                      Real Madrid
                  </Button>
              </NavbarItem>
              <NavbarItem>
                  <Button
                      as={Link}
                      href="/club/40"
                      radius="full"
                      color="primary"
                      variant="light"
                      className="text-white text-base font-medium"
                  >
                      FC Barcelona
                  </Button>
              </NavbarItem>
              <NavbarItem>
                  <Button
                      as={Link}
                      href="/club/1"
                      radius="full"
                      color="primary"
                      variant="light"
                      className="text-white text-base font-medium"
                  >
                      Arsenal
                  </Button>
              </NavbarItem>
              <NavbarItem>
                  <Button
                      as={Link}
                      href="/club/15"
                      radius="full"
                      color="primary"
                      variant="light"
                      className="text-white text-base font-medium"
                  >
                      Manchester City
                  </Button>
              </NavbarItem>
              <NavbarItem>
                  <Button
                      as={Link}
                      href="/club/65"
                      radius="full"
                      color="primary"
                      variant="light"
                      className="text-white text-base font-medium"
                  >
                      Bayern Munich
                  </Button>
              </NavbarItem>
          </NavbarContent>
          <NavbarContent justify="end">
              <NavbarItem>
                  <Button
                      as={Link}
                      href="/report"
                      radius="full"
                      color="secondary"
                      variant="ghost"
                      className="text-white text-base font-medium"
                  >
                      Report Decision
                  </Button>
              </NavbarItem>
          </NavbarContent>
      </Navbar>
      <main className="min-h-screen">
          {children}
      </main>
      </body>
    </html>
  );
}
